name: "Create PR"
on: push

jobs:
  create-pr-on-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
      
    - name: Creates Pull Request
      uses: emiliopedrollo/create-pull-request@v1.1.0

